#ifndef XENON_DEFINITIONS_H
#define XENON_DEFINITIONS_H

//Window
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 800

//Splash
#define SPLASH_DURATION 3

//Game
#define FRAME_TIME 1.f/60.f
#define FRAME_DELAY 0.25

//Select Spaceship
#define ROTATION_RATIO 0.5

//Gameloop
#define INITIAL_ASTEROIDS 6
#define ASTEROID_SPAWN 10
#define ALIEN_SPAWN 15
#define POINT_BONUS 5
#define POINT_MALUS -2
#define ASTEROID_EXPL 10
#define RUBBLE_EXPL 7
#define ALIEN_EXPL 15
#define TIME_BEFORE_GAMEOVER 4

//Panel
#define SHIELD_ICO_AXIS 1050
#define PANEL_ORD 10
#define SCORE_AXIS 50

//Pause
#define TOGGABLE_SHIELD_COST 30
#define BUY_TOGG_SHIELD_STRING "Buy Toggable Shield    30p"
#define ADD_TOGG_SHIELD_STRING "Add a Toggable Shield  30P"
#define TIME_SHIELD_COST 30
#define BUY_TIME_SHIELD_STRING "Buy Time Shield        30p"
#define ADD_TIME_SHIELD_STRING "Add 2 seconds          30p"

//Settings
#define FIRST_VOLUME_BOX_AXIS 372
#define FIRST_VOLUME_BOX_ORD 263
#define VOLUME_BOX_GAP 65
#define DEFAULT_MUSIC_VOLUME 100
#define DEFAULT_FX_VOLUME 75

//Shields
#define TIME_SHIELD_BASE_DURATION 3
#define ADD_TIME_SHIELD_DURATION 2

//Entities
#define RADIANS 0.0174533

#define ROCK_SPRITE_WIDTH 64
#define ROCK_SPRITE_HEIGTH 64
#define ROCK_SPRITESHEET 16
#define ROCK_ANIM_SPEED 0.2

#define EXPLOSION_SPRITE_WIDTH 256
#define EXPLOSION_SPRITE_HEIGHT 256
#define EXPLOSION_SPRITESHEET 45
#define NORMAL_EXPLOSION_ANIM_SPEED 1
#define SLOW_EXPLOSION_ANIM_SPEED 0.25

#define PROJECTILE_SPEED 7
#define PROJECTILE_SPRITE_WIDTH 32
#define PROJECTILE_SPRITE_HEIGHT 64
#define PROJECTILE_SPRITESHEET 16
#define PROJECTILE_ANIM_SPEED 1
#define ALIEN_PROJECTILE_SPEED 8
#define ALIEN_PROJECTILE_SPRITE_WIDTH 64
#define ALIEN_PROJECTILE_SPRITE_HEIGHT 64
#define ALIEN_PROJECTILE_SPRITESHEET 16
#define ALIEN_PROJECTILE_ANIM_SPEED 1

#define ALIEN_SPRITE_WIDTH 57
#define ALIEN_SPRITE_HEIGHT 57
#define ALIEN_SPRITESHEET 1
#define ALIEN_ANIM_SPEED 0
#define ALIEN_ACCEL 2
#define ALIEN_FIRE_RATE 0.8
#define TRIGGERING_DISTANCE 350

#define DECEL_FACTOR 0.98

#define LENNON_SPRITE_WIDTH 58
#define LENNON_SPRITE_HEIGHT 79
#define LENNON_FIRE_RATE 0.4
#define LENNON_MAX_SPEED 10
#define LENNON_ACCEL 0.14
#define LENNON_BEND 2

#define MACCA_SPRITE_WIDTH 36
#define MACCA_SPRITE_HEIGHT 66
#define MACCA_FIRE_RATE 0.3
#define MACCA_MAX_SPEED 15
#define MACCA_ACCEL 0.11
#define MACCA_BEND 1.8

#define HARRISON_SPRITE_WIDTH 52
#define HARRISON_SPRITE_HEIGHT 66
#define HARRISON_FIRE_RATE 0.5
#define HARRISON_MAX_SPEED 13
#define HARRISON_ACCEL 0.12
#define HARRISON_BEND 1.5

#define STARR_SPRITE_WIDTH 32
#define STARR_SPRITE_HEIGHT 44
#define STARR_FIRE_RATE 0.2
#define STARR_MAX_SPEED 16
#define STARR_ACCEL 0.15
#define STARR_BEND 2.2

#endif